### ISSUE TITLE
配置成功后，连接正常，提交反馈401

### ISSUE THREAD

**Issue by webYouth** [MTWGA/thoughtworks-code-review-tools#136]
**Describe the bug**
配置成功后，连接正常，提交反馈401

**To Reproduce**

**Expected behavior**

**Screenshots**
![connected](https://github.com/MTWGA/thoughtworks-code-review-tools/assets/22173368/6faf5c9a-6fca-4249-8159-fe31c6b994e0)

![data](https://github.com/MTWGA/thoughtworks-code-review-tools/assets/22173368/b4990e6b-ea14-49b5-baa4-b4e6d659a8c6)
![feedback](https://github.com/MTWGA/thoughtworks-code-review-tools/assets/22173368/7a837178-fa0b-4589-aa0f-864a3a0596f7)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lhui** [comment]
可以尝试重新生成下 trello token 再测试下，当前发现有时 token 过长会导致 401 的问题

**Comment by webYouth** [comment]
确实是过长导致的，辛苦作者了
